version: '3.8'
services:
  per2profit:
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 3
    image: enwaiax/peer2profit
    environment: 
      - email=chasing0806@gmail.com
    command: ["/app/p2pclient", "-l", "$email"]
